### ISSUE TITLE
It's not working, Please fix this

### ISSUE THREAD

**Issue by romanrokon** [hobbyquaker/amixer-web#1]
The server starting listening but when going to port 3000 it crashing. error message...

(node:1303556) UnhandledPromiseRejectionWarning: Error: ALSA lib control.c:1379:(snd_ctl_open_noupdate) Invalid CTL equal
amixer: Mixer attach equal error: No such file or directory

    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/amixer-web/lib/mixer.js:36:28)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12)
(node:1303556) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1303556) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Node v12.18.0

**Comment by adminy** [comment]
That's you passing in the wrong arguments ... your -D argument is incorrect. This works great.
